spring.application.name=weather-app
server.port=4002

spring.datasource.url=jdbc:mysql://localhost:3306/weather_app
spring.datasource.username=weather_user
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

weather.api.key=646c88278b54c28fcb119c49e25194f3